trigger:
- master

jobs:
  - job: build
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: |
        sudo apt update -y
        sudo apt install -y fftw3 gfortran gcc-8 libxpm-dev

    - task: CMake@1
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/build-cmake-debug'
        cmakeArgs: '$(Build.SourcesDirectory) -DCMAKE_BUILD_TYPE=Debug -Droofit=ON -Dminuit2=ON -DLLVM_BUILD_TYPE=Debug -Dtesting=ON'

    - task: CmdLine@2
      inputs:
        script: 'make'
        workingDirectory: '$(Build.SourcesDirectory)/build-cmake-debug'
        failOnStderr: true
